# Generated by Django 3.0.4 on 2020-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=0, max_digits=2)),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
