# Generated by Django 3.0.4 on 2020-06-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0002_auto_20200609_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='champions',
            new_name='product',
        ),
    ]
