# Generated by Django 3.0.4 on 2020-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0003_auto_20200609_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=50)),
                ('uEmail', models.CharField(max_length=50)),
                ('uPhone', models.CharField(max_length=50)),
                ('uAddress1', models.CharField(max_length=50)),
                ('uAddress2', models.CharField(max_length=50)),
                ('uCity', models.CharField(max_length=50)),
                ('uState', models.CharField(max_length=50)),
                ('uZip', models.CharField(max_length=50)),
                ('uCardType', models.CharField(max_length=50)),
                ('uNameOnCard', models.CharField(max_length=50)),
                ('uCardNumber', models.CharField(max_length=50)),
                ('uExpiration_date', models.CharField(max_length=50)),
                ('uCvc_number', models.CharField(max_length=50)),
                ('uDelivery_option', models.CharField(max_length=50)),
            ],
        ),
    ]
