# Generated by Django 3.0.7 on 2020-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0003_account_hash_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
