# Generated by Django 3.0.4 on 2020-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0004_account_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='new_salt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
