# Generated by Django 3.0.4 on 2020-06-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0005_account_new_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='new_hash_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
