# Generated by Django 3.0.4 on 2020-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0008_auto_20200630_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
