# Generated by Django 3.0.4 on 2020-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0010_auto_20200701_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
