# Generated by Django 3.0.4 on 2020-07-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0012_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hash_value',
        ),
        migrations.RemoveField(
            model_name='account',
            name='salt',
        ),
    ]
