# Generated by Django 3.0.4 on 2020-07-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolshopping', '0013_auto_20200701_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
